apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-approle-store
  namespace: demo
spec:
  provider:
    vault:
      server: "http://vault-active.vault.svc.cluster.local:8200"
      path: "services"
      version: "v2"
      auth:
        appRole:
          path: "approle"                  # AppRole mount path in Vault
          roleId: "2443e5d8-e83e-ccf3-bbf1-e455dd8c040f"             # Role ID (non-sensitive)
          secretRef:
            name: vault-approle-secret     # K8s secret holding the Secret ID
            key: secretId
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-approle-secret
  namespace:  demo
type: Opaque
stringData:
  secretId: "923b40d6-19e5-ee59-b2cf-ddc6552c261a"
